version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartcurr
      - JWT_SECRET=devsecret
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

volumes:
  mongo_data:
